name: Test matrix
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    strategy:
      matrix:
        environment: [ENV1, ENV2, ENV3, ENV4]
    steps:
      - name: step1.1
        run: echo "123456" > ${{ vars.APK_NAME }}

      - name: Generate artifact release 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ vars.APK_NAME }}
          path: ${{ vars.APK_NAME }}

      - name: step1.2
        run: echo "567890" > ${{ vars.APK_DEBUG_NAME }}

      - name: Generate artifact release 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ vars.APK_DEBUG_NAME }}
          path: ${{ vars.APK_DEBUG_NAME }}