name: Test matrix - Preparation
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        options:
          - 'ENV1'
          - 'ENV4'
          - 'ENV1,ENV2,ENV3'
          - 'ENV1,ENV3'
        type: choice
jobs:
  matrix:
    name: Prepare Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: |
          ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: matrix
        id: matrix
        run: |
          envs="${{ inputs.environment }}"
          matrix=$(echo $envs | jq -cR 'split(",") | .[]' | jq -s '[.[] | { environment: . }]' | jq -c '{ include: . }')
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
          echo $matrix

  takevalue:
    name: Take Value
    needs: [matrix]
    runs-on: ubuntu-latest
    steps:
      - name: take
        id: take
        run: echo ${{ needs.matrix.outputs.matrix }}

  build:
    needs: [matrix]
    if: ${{ fromJson(needs.matrix.outputs.matrix).include[0] }}
    uses: ./.github/workflows/matrix-release.yml
    with:
      environment: ${{ matrix.environment }}
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}

  Create-Release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: tempartifacts

      - name: Create Pre-Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: tempartifacts/
          allowUpdates: true
          generateReleaseNotes: true
          prerelease: true
          tag: v1
