name: Test matrix
on:
  workflow_dispatch
    inputs:
      environments:
        description: 'Environment'
        required: true
        options:
          - ENV1
          - ENV2
          - ENV3
          - ENV4
        type: choice
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    strategy:
      matrix:
        environment: [ENV1, ENV2, ENV3, ENV4]
    steps:
      - name: step1.1
        run: echo "123456" > ${{ vars.FILE_PART1 }}

      - name: Generate artifact release 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ vars.FILE_PART1 }}
          path: ${{ vars.FILE_PART1 }}

      - name: step1.2
        run: echo "567890" > ${{ vars.FILE_PART2 }}

      - name: Generate artifact release 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ vars.FILE_PART2 }}
          path: ${{ vars.FILE_PART2 }}
