name: Test matrix - Preparation
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        options:
          - 'ENV1'
          - 'ENV4'
          - 'ENV1,ENV2,ENV3'
          - 'ENV1,ENV3'
        type: choice
jobs:
  matrix:
    name: Prepare Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: |
          ${{ steps.matrix.outputs.matrix }}
    steps:
      - run: |
          envs="${{ inputs.environment }}"
          matrix=$(echo $envs | jq -cR 'split(",") | .[]' | jq -s '[.[] | { environment: . }]' | jq -c '{ include: . }')
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
          echo $matrix

  build:
    runs-on: ubuntu-latest
    needs: [matrix]
    uses: ./.github/workflows/matrix-release.yml@master
    with:
      environment: ${{ matrix.environment }}
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
