name: Test matrix
on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: step1.1
        run: echo "123456" > ${{ vars.FILE_PART1 }}

      - name: Generate artifact release 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ vars.FILE_PART1 }}
          path: ${{ vars.FILE_PART1 }}

      - name: step1.2
        run: echo "567890" > ${{ vars.FILE_PART2 }}

      - name: Generate artifact release 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ vars.FILE_PART2 }}
          path: ${{ vars.FILE_PART2 }}
