name: Mi workflow
env:
  filename-apk-releasedebuggable: "valor1"
  filename-apk-release:           "valor2"

on:
  workflow_dispatch:
    inputs:
      upload_debug:
        description: 'Upload debug version'
        type: boolean
        required: true
        default: false
      upload_release:
        description: 'Upload to Production'
        type: boolean
        required: true
        default: false
jobs:
  JobTestString:
    runs-on: ubuntu-latest
    steps:
      - name: Uno
        run: |
          # Inicializa un array vacío
          ARRAY=()
          # Añade valores al array basados en los parámetros
          if [ "${{ inputs.upload_debug }}" = "true" ]; then
            ARRAY+=("${{ env.filename-apk-releasedebuggable }}")
          fi
          if [ "${{ inputs.upload_release }}" = "true" ]; then
            ARRAY+=("${{ env.filename-apk-release }}")
          fi
          # Convierte el array en una cadena separada por comas
          STRING=$(IFS=,; echo "${ARRAY[*]}")
          echo $STRING
