name: Mi workflow
env:
  filename-apk-releasedebuggable: "valor1"
  filename-apk-release:           "valor2"

on:
  workflow_dispatch:
    inputs:
      upload_debug:
        description: 'Upload debug version'
        type: boolean
        required: true
        default: false
      upload_release:
        description: 'Upload to Production'
        type: boolean
        required: true
        default: false
jobs:
  JobTestString:
    runs-on: ubuntu-latest
    steps:
      - name: Uno
        run: echo uno
